### ISSUE TITLE
Getting error when trying to run the Compiled main class from the Terminal?

### ISSUE THREAD

**Issue by dilipbobby** [datumbox/datumbox-framework-examples#1]
I cloned the examples and wanted to run an example from the Terminal (working fine in Eclipse) getting following exception.

**INFO  c.d.f.c.d.Dataframe$Builder - Dataset Parsing negative class
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
    at java.io.File.<init>(File.java:418)
    at com.datumbox.framework.common.dataobjects.Dataframe$Builder.parseTextFiles(Dataframe.java:93)
    at com.datumbox.framework.applications.nlp.TextClassifier.fit(TextClassifier.java:143)
    at com.datumbox.examples.TextClassification.main(TextClassification.java:99)**

**Comment by datumbox** [comment]
Unfortunately I can't reproduce the problem. If it persists submit more information.
